"""Add missing columns to LeaseAgreement table

Revision ID: 0bb09978c31c
Revises: f72a11ae8f87
Create Date: 2025-03-04 08:12:04.424701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb09978c31c'
down_revision = 'f72a11ae8f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease_agreement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_proof', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('invoice_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('signature_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('signature_ip', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease_agreement', schema=None) as batch_op:
        batch_op.drop_column('signature_ip')
        batch_op.drop_column('signature_date')
        batch_op.drop_column('invoice_file')
        batch_op.drop_column('payment_verified')
        batch_op.drop_column('payment_proof')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
