"""Fresh start with updated Student model

Revision ID: ad177b9f802c
Revises: 
Create Date: 2025-03-05 13:12:42.158530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad177b9f802c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease_agreement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('guardian_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('admin_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('student_signature_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_signature_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('signature_date')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('student_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('institution', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('campus', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('year_of_study', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('accommodation_preference', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('guardian_id_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('guardian_street_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('guardian_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('proof_of_registration', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'accommodation', ['accommodation_preference'], ['id'])
        batch_op.drop_column('payslip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payslip', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proof_of_registration')
        batch_op.drop_column('guardian_city')
        batch_op.drop_column('guardian_street_address')
        batch_op.drop_column('guardian_id_number')
        batch_op.drop_column('accommodation_preference')
        batch_op.drop_column('year_of_study')
        batch_op.drop_column('course')
        batch_op.drop_column('campus')
        batch_op.drop_column('institution')
        batch_op.drop_column('student_number')
        batch_op.drop_column('id_number')

    with op.batch_alter_table('lease_agreement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('admin_signature_date')
        batch_op.drop_column('student_signature_date')
        batch_op.drop_column('admin_signature')
        batch_op.drop_column('guardian_signature')
        batch_op.drop_column('student_signature')

    # ### end Alembic commands ###
